version: '3'

networks:
  frontend:
    driver: ${NETWORKS_DRIVER}
  backend:
    driver: ${NETWORKS_DRIVER}


volumes:
  mongo:
    driver: ${VOLUMES_DRIVER}

services:

  ### MongoDB ##############################################
    mongo:
      build: ./apps/mongo
      ports:
        - "${MONGODB_PORT}:27017"
      volumes:
        - ${DATA_PATH_HOST}/mongo:/data/db
      networks:
        - backend
  ### Strapi Utilities ##################################
    strapi:
      build:
        context: ./apps/backend
      volumes:
        - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
      ports:
        - 1337:1337
      networks:
        - frontend
        - backend
      depends_on:
        - mongo
      restart: always
  ### MongoWebUI ################################################
    mongo-webui:
      build:
        context: ./apps/mongo-webui
      environment:
        - ROOT_URL=${MONGO_WEBUI_ROOT_URL}
        - MONGO_URL=${MONGO_WEBUI_MONGO_URL}
        - INSTALL_MONGO=${MONGO_WEBUI_INSTALL_MONGO}
      volumes:
        - ${DATA_PATH_HOST}/mongo-webui:/data/db
      ports:
        - "${MONGO_WEBUI_PORT}:3000"
      networks:
        - backend
      depends_on:
        - mongo
